# permissions for end users to edit capitemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: capitemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: templates-controller
    app.kubernetes.io/part-of: templates-controller
    app.kubernetes.io/managed-by: kustomize
  name: capitemplate-editor-role
rules:
- apiGroups:
  - capi.weave.works
  resources:
  - capitemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capi.weave.works
  resources:
  - capitemplates/status
  verbs:
  - get
