---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - capi.weave.works
  resources:
  - capitemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - capi.weave.works
  resources:
  - capitemplates/finalizers
  verbs:
  - update
- apiGroups:
  - capi.weave.works
  resources:
  - capitemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - templates.weave.works
  resources:
  - gitopstemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - templates.weave.works
  resources:
  - gitopstemplates/finalizers
  verbs:
  - update
- apiGroups:
  - templates.weave.works
  resources:
  - gitopstemplates/status
  verbs:
  - get
  - patch
  - update
