# permissions for end users to view gitopstemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gitopstemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: templates-controller
    app.kubernetes.io/part-of: templates-controller
    app.kubernetes.io/managed-by: kustomize
  name: gitopstemplate-viewer-role
rules:
- apiGroups:
  - templates.weave.works
  resources:
  - gitopstemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.weave.works
  resources:
  - gitopstemplates/status
  verbs:
  - get
