name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          cache: true
      - name: Test
        run: make test

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # for git describe
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          cache: true
      - name: Build
        run: make docker-build
      - name: Docker login
        # .netrc is used by docker-build, ~/.netrc is used by go test
        # run: echo "machine github.com login wge-build-bot password ${{ secrets.BUILD_BOT_TOKEN }}" | tee ~/.netrc .netrc
        run: echo "${{ secrets.BUILD_BOT_TOKEN }}" | docker login ghcr.io -u wge-build-bot --password-stdin
      - name: push
        run: IMG=ghcr.io/weaveworks/templates-controller:$(git describe --always) make docker-push
